### ISSUE TITLE
vcg::face::JumpingPos Discrepancy

### ISSUE THREAD

**Issue by pingchia** [OpenMVS/openMVS#1]
If pull "vcglib" source as mentioned in "https://github.com/cdcseacave/openMVS/wiki/Building" (BTW, the link from https://github.com/OpenMVS/openMVS to https://openmvs.github.io/openMVS/wiki/Building is not working) for Linux platform:

    svn checkout svn://svn.code.sf.net/p/vcg/code/trunk/vcglib vcglib

Then during compilation of openMVS, the following error message occurs:

    /home/ping/3d/openMVS/libs/MVS/Mesh.cpp: In member function ‘void MVS::Mesh::Clean(float, float, bool, unsigned int, unsigned int)’:
    /home/ping/3d/openMVS/libs/MVS/Mesh.cpp:1055:5: error: ‘JumpingPos’ is not a member of ‘vcg::face’
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
     ^
    /home/ping/3d/openMVS/libs/MVS/Mesh.cpp:1055:38: error: expected primary-expression before ‘>’ token
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
                                      ^
    /home/ping/3d/openMVS/libs/MVS/Mesh.cpp:1055:65: error: ‘p’ was not declared in this scope
     vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);

The reason of these errors are in "openMVS/libs/MVS/Mesh.cpp" lines 1055-1064:

				vcg::face::JumpingPos<CLEAN::Face> p(start, vi->cVFi(), &*vi);
				int count(0);
				do {
					++count;
					p.NextFE();
				} while (p.f!=start);
				if (count == 1) {
					vcg::tri::Allocator<CLEAN::Mesh>::DeleteVertex(mesh, *vi);
					++nSpikes;
				}

The definition of "vcg::face::JumpingPos" is only seen in "http://docs.ros.org/diamondback/api/vcglib/html/group__face.html", but not in "svn.code.sf.net/p/vcg/code/trunk/vcglib", seems to be a discrepancy.

**Comment by pmoulon** [comment]
Hi @pingchia 
Thanks for your feedback.

Regarding the website, I will do the required update.

Regarding the JumpingPos 
It is defined in .../vcglib/vcg/simplex/face/jumping_pos.h
And it is still defined in the trunk of sourceforge CVGLIB here http://sourceforge.net/p/vcg/code/HEAD/tree/trunk/vcglib/vcg/simplex/face/jumping_pos.h

Please check that -DVCG_DIR="$main_path/vcglib" is pointing to the right path.
perhaps you have two different version of VCG on your computer.

**Comment by pingchia** [comment]
Dear Dr. Moulon,

According to the Building document in https://github.com/cdcseacave/openMVS/wiki/Building <https://github.com/cdcseacave/openMVS/wiki/Building>

Using 

svn checkout svn://svn.code.sf.net/p/vcg/code/trunk/vcglib vcglib

to pull out the VCG code will cause problem on my Ubuntu system. I will try your suggestion site from 

> http://sourceforge.net/p/vcg/code/HEAD/tree/trunk/vcglib/vcg/simplex/face/jumping_pos.h <http://sourceforge.net/p/vcg/code/HEAD/tree/trunk/vcglib/vcg/simplex/face/jumping_pos.h>

Thank you.

Ping

**Comment by pmoulon** [comment]
Does your problem is now solved?
