### ISSUE TITLE
absolute working directory 

### ISSUE THREAD

**Issue by mojovski** [OpenMVS/openMVS#10]
When using InterfaceVisualSFM, the full working directory is constructed in a wrong way.
This is the case when the working directory is passed  as an absolute path.
eg:
```
bin/InterfaceVisualSFM -i scene.nvm -w /home/mojovski/datasets/IMAGES1
```
The resulting full working directory and thus the path to an image is then
```
/home/mojovski/Projekte/cpp/openMVS/_build//home/mojovski/datasets/IMAGES1/frame0000.jpg
```
when InterfaceVisualSFM is called from
```
/home/mojovski/Projekte/cpp/openMVS/_build
```

I guess the reason is in Util.h:308
```cpp
static inline bool isFullPath(LPCTSTR path) {
		// returns true if local drive full path or network path
		return (path && (path[1]==_T(':') ||
			#ifdef UNICODE
			*((DWORD*)path)==0x5C005C00/*"\\\\"*/));
			#else
			*((WORD*)path)==0x5C5C/*"\\\\"*/));
			#endif // UNICODE
	}
```
which does not recognize the passed path as a full absolute path.
It looks like it checks for ":", which is reasonable for windows, nut Linux (ubuntu in my case).

**Comment by cdcseacave** [comment]
That issue was solved several days ago, please use the original repository cdcseacave/openMVS the develop branch. That is always up to date.

**Comment by mojovski** [comment]
thanks!

**Comment by mojovski** [comment]
hmm.. sorry, I have still the issue in branch "develop". Do I miss something?

**Comment by cdcseacave** [comment]
A debug scene would help.
