### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by DirtyHarryLYL** [OpenMVS/openMVS#12]
Hi ,thanks for the cool job first,
     I meet a crush with a big data set of 500 pictures, the log is 
[App     ] Build date: 
[App     ] CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
[App     ] RAM: 9.95GB Physical Memory 128.00TB Virtual Memory
[App     ] OS: Windows 8.1 x64
[App     ] SSE & AVX compatible CPU & OS detected
[App     ] Command line: uav.nvm
[App     ] Loading cameras/points: uav.nvm

[App     ] Build date: 
[App     ] CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
[App     ] RAM: 9.95GB Physical Memory 128.00TB Virtual Memory
[App     ] OS: Windows 8.1 x64
 [App     ] SSE & AVX compatible CPU & OS detected
[App     ] Command line: 1.nvm
[App     ] Loading cameras/points: 1.nvm

then it crush ,can't convert the nvm. Please help me,  is the set too big or 
my pc too weak?
Or something else.
Thx.

**Comment by cdcseacave** [comment]
Please see the VSFM group post. Could you share the project/images so that I can debug?

**Comment by DirtyHarryLYL** [comment]
A nvm and pic have been sent to your VSFM group account. Thx
