### ISSUE TITLE
Compile Error camera.h

### ISSUE THREAD

**Issue by waqarsqureshi** [OpenMVS/openMVS#4]
I installed the previous commit and it was OK,

This time i reinstalled into a new machine and found newer commits. I faced the following errors

/home/te5100server1/openMVS/libs/MVS/Camera.h: In member function ‘SEACAVE::TPoint2<TYPE> MVS::CameraIntern::NormalizeProjection(const SEACAVE::TPoint2<TYPE>&) const’:
/home/te5100server1/openMVS/libs/MVS/Camera.h:186:23: error: ‘mK’ was not declared in this scope
   NormalizeProjection(mK.val, proj.ptr(), pt.ptr());

I fixed by removing "m"

regards

**Comment by pmoulon** [comment]
mK should be replace with invK
