### ISSUE TITLE
Densification hanging

### ISSUE THREAD

**Issue by rperrot** [OpenMVS/openMVS#5]
I tried to make a densification of a point cloud obtained by openMVG but at some point the process is hanging and nothing seams to happened. I keep the process all night long but it doesn't change anything. 

I tried to set number of thread to 1, I also tried to change the resolution but without success. 

Have you been issued something similar ? If true, what can I do ?

**Comment by pmoulon** [comment]
Did you also encounter this compilation error?
https://github.com/OpenMVS/openMVS/issues/4
mK => invK

**Comment by rperrot** [comment]
Yes but I did it too fast :( , I used K like waqarsqureshi did. I compiled again and restart the process. I hope it will solve the issue.

**Comment by rperrot** [comment]
It seems that is doesn't solve the problem. The densification is still waiting on a pair. Doing trivial profiling gives that the process is inside the 

```
DepthMapsData::InitDepthMap( MVS::DepthData & )
``` 
function. 

I'll try to do more precise profiling to see where is exactly the issue, but any suggestion is welcome !

**Comment by rperrot** [comment]
After some std::cerr it seems that code is stuck inside this loop : 

```
    for (CGAL::Delaunay::Face_iterator it=delaunay.faces_begin(); it!=delaunay.faces_end(); ++it) 
    {
        ...
    }
```

If it has run more than a night, I suspect an infinite loop here ?

**Comment by rperrot** [comment]
I think I understand a little bit more where something is hanging. 

I output the position of the points to be rasterized,
