### ISSUE TITLE
RefineMesh

### ISSUE THREAD

**Issue by waqarsqureshi** [OpenMVS/openMVS#8]
RefineMesh: /home/te5100server1/openMVS/libs/MVS/../Common/List.h:970: ARG_TYPE SEACAVE::cList<TYPE, ARG_TYPE, useConstruct, grow, IDX_TYPE>::RemoveTail() [with TYPE = SEACAVE::TImage<double>*; ARG_TYPE = SEACAVE::TImage<double>*; int useConstruct = 1; int grow = 16; IDX_TYPE = long unsigned int]: Assertion `!useConstruct' failed.
Aborted (core dumped)

The RefinMesh Generate an assersion. It also save a file name RefineMesh2.ply in the temp directory.
With the standard ImageDatasetCastle, after the new commits and modifications.

**Comment by pmoulon** [comment]
Assertion happens because you are not in release mode.
Configure your cmake in order to do not be blocked by the assert (-DCMAKE_BUILD_TYPE=RELEASE)

**Comment by cdcseacave** [comment]
This problem was solved in a commit around 2 weeks ago.
