### ISSUE TITLE
Different focal length for x and y?

### ISSUE THREAD

**Issue by mojovski** [OpenMVS/openMVS#9]
Hi, is there a way to integrate focal length for vertical and horizontal parameters?
fx and fy?
As far as I can see, the camera class supports only one:
```
CameraT_::SetFocalLength(Float F)
```

Thanks alot!

**Comment by cdcseacave** [comment]
CameraT_ is not part of my code, it is how VisualSFM stores a camera. OpenMVS uses a camera with full K matrix. Check Interface.h

**Comment by mojovski** [comment]
ok, thanks! I think I will adopt the CameraT class to my needs...
